[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/admin/"
  status = 302
  force = false
  conditions = {Identity = true}

[context.production.environment]
  NODE_ENV = "production"

# Configurazione per Identity
[identity]
  # Abilita Git Gateway
  git-gateway = true
